name: global_calculator
description: "A new Flutter project."

# Prevents accidental publication to pub.dev
publish_to: 'none'

# Versioning information
version: 1.0.0+1

environment:
  sdk: ^3.5.1

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  provider: ^6.0.0
  google_fonts: ^2.1.0
  flutter_lints: ^4.0.0

# Flutter-specific configurations
flutter:
  uses-material-design: true

  # Add assets section if needed
  assets:
   - images/
  #   - images/a_dot_ham.jpeg

  # Add custom fonts section if needed
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
