name: global_calculator
description: "A new Global Calculator."

# Prevents accidental publication to pub.dev
publish_to: 'none'

# Versioning information
version: 1.0.0+1

environment:
  sdk: ^3.5.1

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.0.0
  google_fonts: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# Flutter-specific configurations
flutter:
  uses-material-design: true

  # Assets section
  assets:
    - assets/images/

  # Custom fonts (if needed)
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
